name: Test
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  main:
    name: Build and test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
    env:
      MIX_ENV: test

    steps:
      - uses: actions/checkout@v2
      - name: Install Erlang & Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: "24.0"
          elixir-version: "1.13.4"
      - name: Cache Mix
        uses: actions/cache@v2
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-
      - name: Install mix dependencies
        run: mix deps.get
      - name: Check
        run: |
          mix format --check-formatted
          mix deps.unlock --check-unused
          mix deps.audit
          mix sobelow --config
          mix coveralls
      - name: Lint
        run: |
          mix compile --warnings-as-errors --all-warnings
          mix credo --strict
      - name: Tests
        run: mix test
